version: '3'
services:
    microengine:
        build: "."
        depends_on:
            - polyswarm
            - clamav
        environment:
            - CLAMD_HOST=clamav:3310
            - IPFS_HOST=ipfs:5001
            - POLYSWARM_HOST=polyswarm:31337
    polyswarm:
        image: "polyswarm/polyswarm:latest"
        command: --network dev
        depends_on:
            - ipfs
        environment:
            - IPFS_HOST=ipfs:5001
        ports:
            - "31337:31337"
        volumes:
            - "./priv_testnet:/ethereum"
            - "./priv_testnet/geth.ipc:/ethereum/geth.ipc"
#            - "~/.ethereum/rinkeby:/ethereum"
#            - "~/.ethereum/rinkeby/geth.ipc:/ethereum/geth.ipc"
#    geth:
#        image: "ethereum/client-go:alpine"
#        ports:
#            - "30303:30303"
#        volumes:
#            - "./priv_testnet:/root/.ethereum"
#            - "~/.ethash:/root/.ethash"
#        command: ["--nodiscover", "--maxpeers", "0", "--mine", "--minerthreads", "1", "--rpc", "--rpcapi", "eth,web3,personal,net"]
    clamav:
        image: "polyswarm/clamav:latest"
        expose:
            - "3310"
    ipfs:
        image: "polyswarm/ipfs:latest"
        environment:
            - IPFS_BIND_IP=0.0.0.0
            - IPFS_BOOTSTRAP_RM_ALL=true
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
        expose:
            - "4001"
            - "5001"
            - "8080"
volumes:
    ipfs-export:
    ipfs-data:
