version: '3'
services:
    microengine:
        build: "."
        depends_on:
            - polyswarm-node
            - clamav
            - ipfs
        environment:
            - CLAMD_HOST=tcp://clamav:3310
            - IPFS_HOST=ipfs:5001
        networks:
            - ipfs
    polyswarm-node:
        image: "polyswarm/polyswarm:latest"
        depends_on:
            - geth
            - ipfs
        environment:
            - IPFS_HOST=ipfs:5001
        volumes:
            - "./priv_testnet:/ethereum"
            - "./priv_testnet/geth.ipc:/ethereum/geth.ipc"
        networks:
            - ipfs
    geth:
        image: "ethereum/client-go:alpine"
        ports:
            - "30303:30303"
        volumes:
            - "./priv_testnet:/root/.ethereum"
            - "~/.ethash:/root/.ethash"
        command: ["--nodiscover", "--maxpeers", "0", "--mine", "--minerthreads", "1", "--rpc", "--rpcapi", "eth,web3,personal,net"]
    clamav:
        image: "polyswarm/clamav:latest"
        ports:
            - "3310:3310"
    ipfs:
        image: "polyswarm/ipfs:latest"
        environment:
            - IPFS_BIND_IP=0.0.0.0
            - IPFS_BOOTSTRAP_RM_ALL=true
        networks:
            - ipfs
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
        ports:
            - "4001:4001"
            - "5001:5001"
            - "8080:8080"
volumes:
    ipfs-export:
    ipfs-data:
networks:
    ipfs:
        driver: bridge
